# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certidao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certidao', models.IntegerField()),
                ('status_certidao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_cpf', models.CharField(max_length=14, verbose_name='CPF do Proprietario')),
                ('pessoa_nome', models.CharField(max_length=150, verbose_name='Nome do Proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_is_regular', models.BooleanField()),
                ('veiculo_placa', models.CharField(max_length=8, verbose_name='Placa do Veiculo')),
                ('tributo_is_pago', models.BooleanField()),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_certidao.Pessoa')),
            ],
        ),
    ]
